export { default as Navbar } from './Navbar/Navbar'
export { default as CryptoDetails } from './CryptoDetails/CryptoDetails'
export { default as Currencies } from './Currencies/Currencies'
export { default as Homepage } from './Homepage/Homepage'
export { default as News } from './News/News'